import type { PresetScenario } from '../types';

export const presetScenarios: PresetScenario[] = [
  {
    name: 'Bootstrapped Startup',
    description: 'Low capital, steady revenue, no external funding. Survival of the leanest.',
    emoji: '🥾',
    params: {
      initialCapital: 25000,
      monthlyRevenueBase: 3000,
      revenueGrowthRate: 3,
      revenueRandomness: 15,
      fixedMonthlyCosts: 4000,
      costSpikeProbability: 5,
      costSpikeMin: 1000,
      costSpikeMax: 3000,
      fundingProbability: 0,
      fundingMin: 0,
      fundingMax: 0,
      marketVolatility: 5,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
  {
    name: 'Aggressive Growth',
    description: 'VC-funded, high burn rate, aiming for explosive growth.',
    emoji: '🚀',
    params: {
      initialCapital: 500000,
      monthlyRevenueBase: 8000,
      revenueGrowthRate: 12,
      revenueRandomness: 35,
      fixedMonthlyCosts: 50000,
      costSpikeProbability: 15,
      costSpikeMin: 10000,
      costSpikeMax: 50000,
      fundingProbability: 8,
      fundingMin: 100000,
      fundingMax: 500000,
      marketVolatility: 20,
      simulationDuration: 48,
      numSimulations: 500,
    },
  },
  {
    name: 'Side Project',
    description: 'Minimal investment, hobby-level revenue, very low costs.',
    emoji: '🌱',
    params: {
      initialCapital: 5000,
      monthlyRevenueBase: 500,
      revenueGrowthRate: 5,
      revenueRandomness: 25,
      fixedMonthlyCosts: 200,
      costSpikeProbability: 2,
      costSpikeMin: 100,
      costSpikeMax: 500,
      fundingProbability: 0,
      fundingMin: 0,
      fundingMax: 0,
      marketVolatility: 3,
      simulationDuration: 24,
      numSimulations: 500,
    },
  },
  {
    name: 'Enterprise SaaS',
    description: 'Solid contracts, high costs, moderate growth with big deals.',
    emoji: '🏢',
    params: {
      initialCapital: 200000,
      monthlyRevenueBase: 30000,
      revenueGrowthRate: 5,
      revenueRandomness: 10,
      fixedMonthlyCosts: 35000,
      costSpikeProbability: 10,
      costSpikeMin: 5000,
      costSpikeMax: 20000,
      fundingProbability: 3,
      fundingMin: 50000,
      fundingMax: 200000,
      marketVolatility: 8,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
  {
    name: 'High-Risk Moonshot',
    description: 'Deep tech bet — massive volatility, rare but huge funding rounds.',
    emoji: '🌕',
    params: {
      initialCapital: 1000000,
      monthlyRevenueBase: 0,
      revenueGrowthRate: 0,
      revenueRandomness: 50,
      fixedMonthlyCosts: 80000,
      costSpikeProbability: 20,
      costSpikeMin: 20000,
      costSpikeMax: 100000,
      fundingProbability: 5,
      fundingMin: 200000,
      fundingMax: 2000000,
      marketVolatility: 30,
      simulationDuration: 60,
      numSimulations: 500,
    },
  },
  {
    name: 'Freelancer to Agency',
    description: 'Growing from solo freelancer to small agency. Gradual scaling.',
    emoji: '💼',
    params: {
      initialCapital: 15000,
      monthlyRevenueBase: 6000,
      revenueGrowthRate: 4,
      revenueRandomness: 20,
      fixedMonthlyCosts: 5000,
      costSpikeProbability: 8,
      costSpikeMin: 2000,
      costSpikeMax: 8000,
      fundingProbability: 1,
      fundingMin: 10000,
      fundingMax: 30000,
      marketVolatility: 10,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
];

export const defaultParams = presetScenarios[0].params;
