import type { PresetScenario } from '../types';

export const presetScenarios: PresetScenario[] = [
  {
    name: 'Chai Tapri to Brand',
    description: 'Start small like Chaayos — low capital, steady daily sales, growing a local food brand.',
    emoji: 'coffee',
    params: {
      initialCapital: 200000,
      monthlyRevenueBase: 30000,
      revenueGrowthRate: 4,
      revenueRandomness: 15,
      fixedMonthlyCosts: 35000,
      costSpikeProbability: 5,
      costSpikeMin: 5000,
      costSpikeMax: 20000,
      fundingProbability: 0,
      fundingMin: 0,
      fundingMax: 0,
      marketVolatility: 5,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
  {
    name: 'Ed-Tech Startup',
    description: 'Inspired by BYJU\'s early days — moderate investment, subscription revenue, high growth potential.',
    emoji: 'graduation-cap',
    params: {
      initialCapital: 2000000,
      monthlyRevenueBase: 100000,
      revenueGrowthRate: 10,
      revenueRandomness: 25,
      fixedMonthlyCosts: 300000,
      costSpikeProbability: 10,
      costSpikeMin: 50000,
      costSpikeMax: 200000,
      fundingProbability: 5,
      fundingMin: 500000,
      fundingMax: 3000000,
      marketVolatility: 15,
      simulationDuration: 48,
      numSimulations: 500,
    },
  },
  {
    name: 'Quick Commerce',
    description: 'Like Zepto/Blinkit — high burn rate, fast growth, frequent funding needed to survive.',
    emoji: 'zap',
    params: {
      initialCapital: 5000000,
      monthlyRevenueBase: 200000,
      revenueGrowthRate: 15,
      revenueRandomness: 30,
      fixedMonthlyCosts: 800000,
      costSpikeProbability: 15,
      costSpikeMin: 100000,
      costSpikeMax: 500000,
      fundingProbability: 8,
      fundingMin: 1000000,
      fundingMax: 5000000,
      marketVolatility: 20,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
  {
    name: 'Freelance to Agency',
    description: 'A freelancer on Upwork growing into a small IT agency — like many Indian service companies.',
    emoji: 'briefcase',
    params: {
      initialCapital: 100000,
      monthlyRevenueBase: 50000,
      revenueGrowthRate: 3,
      revenueRandomness: 20,
      fixedMonthlyCosts: 40000,
      costSpikeProbability: 8,
      costSpikeMin: 10000,
      costSpikeMax: 50000,
      fundingProbability: 1,
      fundingMin: 50000,
      fundingMax: 200000,
      marketVolatility: 8,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
  {
    name: 'Fintech Disruptor',
    description: 'Inspired by Razorpay/Paytm — strong funding pipeline, high costs, winner-takes-all market.',
    emoji: 'indian-rupee',
    params: {
      initialCapital: 10000000,
      monthlyRevenueBase: 500000,
      revenueGrowthRate: 8,
      revenueRandomness: 20,
      fixedMonthlyCosts: 1500000,
      costSpikeProbability: 12,
      costSpikeMin: 200000,
      costSpikeMax: 1000000,
      fundingProbability: 6,
      fundingMin: 2000000,
      fundingMax: 20000000,
      marketVolatility: 18,
      simulationDuration: 48,
      numSimulations: 500,
    },
  },
  {
    name: 'D2C Brand',
    description: 'Like Mamaearth/boAt — direct-to-consumer, social media driven, moderate investment.',
    emoji: 'shopping-bag',
    params: {
      initialCapital: 500000,
      monthlyRevenueBase: 80000,
      revenueGrowthRate: 7,
      revenueRandomness: 25,
      fixedMonthlyCosts: 100000,
      costSpikeProbability: 10,
      costSpikeMin: 20000,
      costSpikeMax: 100000,
      fundingProbability: 3,
      fundingMin: 200000,
      fundingMax: 1000000,
      marketVolatility: 12,
      simulationDuration: 36,
      numSimulations: 500,
    },
  },
];

export const defaultParams = presetScenarios[0].params;
